#cloud-config
#
# userdata config for backup-server: installs rdiff-backup

# run apt-get upgrade at first boot
apt_upgrade: true

#apt_sources:
# - source: deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ lucid multiverse
# - source: deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ lucid multiverse
# - source: deb http://security.ubuntu.com/ubuntu lucid-security multiverse
# - source: deb-src http://security.ubuntu.com/ubuntu lucid-security multiverse

packages:
 - rdiff-backup
