#cloud-config
#
# userdata config for backup-server: installs rdiff-backup and sets a shutdown job for 24 hours hence

# run apt-get upgrade at first boot
# apt_upgrade: true

#apt_sources:
# - source: deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ lucid multiverse
# - source: deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ lucid multiverse
# - source: deb http://security.ubuntu.com/ubuntu lucid-security multiverse
# - source: deb-src http://security.ubuntu.com/ubuntu lucid-security multiverse

packages:
 - rdiff-backup
 - at

runcmd:
 # shut the instance down in a long time; this will ensure that if we fall off the net
 # we don't end up with a dangling instance.
 - echo "/sbin/shutdown -h +5" | at now + 48 hours

 # create a .ssh directory for the backup user
 - mkdir -p ~backup/.ssh
 - touch ~backup/.ssh/authorized_keys
 - chown -R backup ~backup/.ssh
 - chmod 600 ~backup/.ssh/authorized_keys

 # and enable a shell
 - chsh -s /bin/bash backup
